[".hammerspoon/stackline"]
type = "archive"
url = "https://github.com/AdamWagner/stackline/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "720h"
[".config/kitty/kitty_search"]
type = "archive"
url = "https://github.com/trygveaa/kitty-kitten-search/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "720h"
[".config/kitty/kitty_grab"]
type = "archive"
url = "https://github.com/yurikhan/kitty_grab/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "720h"
