fork = false
idle = true
maximized = false
{{- if eq .chezmoi.os "darwin" }}
frame = "none"
neovim-bin = "/opt/homebrew/bin/nvim"
srgb = false
wsl = false
{{- else if eq .chezmoi.os "windows" }}
frame = "full"
neovim-bin = "/home/linuxbrew/.linuxbrew/bin/nvim"
srgb = true
wsl = true
{{- end }}
no-multigrid = false
tabs = false
theme = "auto"
title-hidden = true
vsync = true

[font]
normal = [] # Will use the bundled Fira Code Nerd Font by default
size = 14.0
